services:
  app:
    build: ./
    volumes:
      - ./:/srv/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: "mysqld --init-file /data/application/init.sql"
